insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (11,'Rondônia','RO',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (12,'Acre','AC',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (13,'Amazonas','AM',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (14,'Roraima','RR',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (15,'Pará','PA',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (16,'Amapá','AP',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (17,'Tocantins','TO',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (21,'Maranhão','MA',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (22,'Piauí','PI',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (23,'Ceará','CE',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (24,'Rio Grande do Norte','RN',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (25,'Paraíba','PB',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (26,'Pernambuco','PE',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (27,'Alagoas','AL',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (28,'Sergipe','SE',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (29,'Bahia','BA',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (31,'Minas Gerais','MG',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (32,'Espírito Santo','ES',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (33,'Rio de Janeiro','RJ',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (35,'São Paulo','SP',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (41,'Paraná','PR',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (42,'Santa Catarina','SC',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (43,'Rio Grande do Sul','RS',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (50,'Mato Grosso do Sul','MS',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (51,'Mato Grosso','MT',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (52,'Goiás','GO',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (53,'Distrito Federal','DF',now(),now());
insert into uf (cod_ibge, descricao, sigla, dt_criacao, dt_alteracao) values (99,'Exterior','EX',now(),now());